language: node_js
dist: trusty
node_js:
  - "10"
install:
  - chmod +x ./build.sh
script:
  - ./build.sh
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: clash-dashboard/dist
  keep-history: true
  fqdn: clashx.skk.moe
  on:
    branch: master